name: build-snapshot

on: 
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        servers: >
          [{ 
            "id": "github-parent-pom-typesystems",
            "username": "${env.GITHUB_ACTOR}",
            "password": "${env.GITHUB_TOKEN}"
          },{
            "id": "github-core-typesystems",
            "username": "${env.GITHUB_ACTOR}",
            "password": "${env.GITHUB_TOKEN}"
          }]
    - run: mvn -B install --no-transfer-progress --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-snapshot:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [{ 
              "id": "github",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            },{
              "id": "github-parent-pom-typesystems",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            },{
              "id": "github-core-typesystems",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            }]
      - name: Publish SNAPSHOT version to GitHub Packages (we can skip tests, since we only deploy, if the build workflow succeeded)
        run: mvn -B --no-transfer-progress deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
