name: Maven CI build

on:
  push:
    branches: [ "main", "release/**" ]
    paths-ignore: [ ".github/**" ]
  pull_request:
    branches: [ "main", "release/**" ]
    paths-ignore: [ ".github/**" ]
  workflow_dispatch:
    inputs:
      deploy-strategy:
        description: 'Deploy strategy can be `always`, `auto` or `skip`. In auto mode, it triggers when the current branch matches `main` or `release/*`.'
        required: true
        type: choice
        default: 'auto'
        options:
          - always
          - auto
          - skip
  workflow_run:
    workflows: ["Maven release build"]
    types:
      - completed

permissions:
  contents: read
  checks: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.runner }}

    steps:
    - name: Skip workflow if the workflow that triggered it was not successsful
      if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success' }}
      run: |
        echo "Aborting: Triggered by workflow_run but previous workflow failed with conclusion '${{ github.event.workflow_run.conclusion }}'."
        exit 78

    - name: Support long paths (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref }}
        lfs: true

    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    
    - uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b # 3.1.0
      with:
        servers: |
          [{
            "id": "github-parent-pom-typesystems", 
            "username": "${env.GITHUB_ACTOR}", 
            "password": "${env.GITHUB_TOKEN}"
          },{
            "id": "github-core-typesystems", 
            "username": "${env.GITHUB_ACTOR}", 
            "password": "${env.GITHUB_TOKEN}"
          }]          

    - name: Build with Maven
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        set -o pipefail &&
        mvn install
        --batch-mode
        --no-transfer-progress
        --fail-at-end
        2>&1 | tee mvn-build.log

    - name: Publish test report
      if: success() || failure() # always run even if the previous step fails
      uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5.5.1
      with:
        commit: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref }}
        fail_on_failure: true
        include_passed: false
        detailed_summary: true
        include_time_in_summary: true
        check_name: |
          Surefire Test Report (${{ matrix.runner }})
          Failsafe Test Report (${{ matrix.runner }})
        report_paths: |
          **/target/surefire-reports/TEST-*.xml
          **/target/failsafe-reports/TEST-*.xml

    - name: Capture test reports
      if: success() || failure() # always run even if the previous step fails
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: Test reports (${{ matrix.runner }})
        path: |
          **/target/surefire-reports/TEST-*.xml
          **/target/failsafe-reports/TEST-*.xml

    - name: Capture mvn-build-log
      if: success() || failure() # always run even if the previous step fails
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: Maven Build Log (${{ matrix.runner }})
        path: mvn-build.log

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: |
        matrix.runner == 'ubuntu-latest' && (
        inputs.deploy-strategy == 'always' || 
        ((inputs.deploy-strategy == '' || inputs.deploy-strategy == 'auto') && 
        (startsWith(github.event.workflow_run.head_branch, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/release/'))))
      run: >
        mvn deploy
        --batch-mode
        -DskipTests
        -P-api-compatibility-check
